version: '3'

services:
  node0:
    container_name: node0
    image: "tendermint/localnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=$${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    image: "tendermint/localnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=$${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: node2
    image: "tendermint/localnode"
    environment:
      - ID=2
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: node3
    image: "tendermint/localnode"
    environment:
      - ID=3
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.5

  node4:
    container_name: node4
    image: "tendermint/localnode"
    environment:
      - ID=4
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26665-26666:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  node5:
    container_name: node5
    image: "tendermint/localnode"
    environment:
      - ID=5
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26667-26668:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  node6:
    container_name: node6
    image: "tendermint/localnode"
    environment:
      - ID=6
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26669-26670:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  node7:
    container_name: node7
    image: "tendermint/localnode"
    environment:
      - ID=7
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26671-26672:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.9

  node8:
    container_name: node8
    image: "tendermint/localnode"
    environment:
      - ID=8
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26673-26674:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.10

  node9:
    container_name: node9
    image: "tendermint/localnode"
    environment:
      - ID=9
      - LOG=$${LOG:-tendermint.log}
    ports:
      - "26675-26676:26656-26657"
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.11

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16

