- name: download prometheus node exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-0.17.0.linux-amd64.tar.gz"

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "/tmp/node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: "/tmp/"
    creates: "/tmp/node_exporter-0.17.0.linux-amd64"

- name: update group and owner for files
  file:
    path: "/tmp/node_exporter"
    state: directory
    recurse: yes
    owner: "{{service}}"
    group: "{{service}}"
    mode: 0755
#
- name: create symlink to the current release
  file:
    src: "/tmp/node_exporter-0.17.0.linux-amd64/node_exporter"
    path: "/usr/bin/node_exporter"
    state: link

- name: create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node exporter

- name: ensure prometheus node exporter service is enabled and started
  service:
    name: node_exporter
    state: started
    enabled: yes
